title: Beesafe
email: hikenike6@gmail.com

description: Computer enthusiast, AI fanatic, technologist, Meta human, Hacker! 
url: https://beesaferoot.github.io/
github_username: beesaferoot

# Build settings
# Removed Gem-based theme, let jekyll use as regular theme
# theme: minima